name: portail_eleve
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^19.3.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  animations: ^2.0.11
  shimmer: ^3.0.0
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.2.1
  flutter_animate: ^4.5.2
  jiffy: ^6.4.3
  logger: ^2.6.0
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  pretty_dio_logger: ^1.4.0
  dio_smart_retry: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/
